### ISSUE TITLE
cmd/fillstruct: broken without modules

### ISSUE THREAD

**Issue by mschneider82** [davidrjenni/reftools#31] opened 2019-05-09 08:14 UTC
I dont have go modules in my project (in $GOPATH/src) and trying to fill a struct in a _test.go file, the struct is defined in the same package but not in the _test.go file.

I always get the message:
>fillstruct: no struct literal found at selection

When i rollback to commit 654d0ba4f96d62286ca33cd46f7674b84f76d399 struct filling in the _test file is working.

```
client.go :
type X struct {
       Somevalue bool
}


client_test.go:
func TestClient_DoSomeTest(t *testing.T) {
   x := X{} // problem filling struct
}

```

**Comment by klische** [comment] 2019-08-05 19:25
I have the same issue. Even if the struct is defined in the same package, but in a different file, I get the `fillstruct: no struct literal found at selection` message. 

I guess a workaround for now is to copy over struct definitions into the same file and then copy them back over to another file in the same package after using this tool.

@davidrjenni can you please look into this?

**Comment by mschneider82** [comment] 2019-08-22 13:13
@klische for me a better workaround is to rollback to the old binary:
```
cd $GOPATH/src/github.com/davidrjenni/reftools/cmd/fillstruct
git checkout 654d0ba
go build -i
```

**Comment by mschneider82** [comment] 2019-08-22 14:06
@klische you could test my PR / fork.
My PR should be compatible with modules and non-modules...

**Comment by davidrjenni** [comment] 2019-08-22 14:34
@mschneider82, @klische sorry for the late response and thank you for the workaround instructions and the PR. I will review the issue and the PR during the weekend. I hope you can still use the tool with the workaround until the issue is resolved.

**Comment by mschneider82** [comment] 2019-08-22 15:00
thanks @davidrjenni i am sure that there is a better solution than my hack, but it works for now.. I cannot live with a half-broken fillstruct tool!

**Comment by mschneider82** [comment] 2019-08-26 07:27
@davidrjenni have you had some time to look at this?

**Comment by klische** [comment] 2019-08-26 08:20
> @klische you could test my PR / fork.
> My PR should be compatible with modules and non-modules...

I will test your PR tomorrow. Thank you for this :)

**Comment by davidrjenni** [comment] 2019-08-26 20:37
@mschneider82 could you please test PR #33? It seems to fix the problem for me.

**Comment by davidrjenni** [comment] 2019-08-27 20:20
@klische can you also confirm that the problem is fixed in the current master?

**Comment by klische** [comment] 2019-08-30 21:00
@davidrjenni I apologize for the late response. I can confirm it is working! This is fantastic. Thank you so much.

**Comment by davidrjenni** [comment] 2019-08-31 12:14
@klische thanks for the feedback!

**Closed by davidrjenni** 2019-08-31 12:14 UTC
